name: finance_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #navigation
  go_router: ^16.2.1

  #ui
  top_snackbar_flutter: ^3.3.0
  flashy_tab_bar2: ^0.0.10

  #state_managment
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  #helpers
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.2.0
  flutter_native_splash: ^2.4.6
  path_provider: ^2.1.5
  dartz: ^0.10.1

  #firebase
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_auth: ^6.0.2


  #notifications
  flutter_local_notifications: ^19.4.1


  #di
  injectable: ^2.5.1
  get_it: ^8.2.0

  #network
  dio: ^5.9.0

  #storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  injectable_generator: ^2.8.1
  build_runner: ^2.7.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/logo.png"

flutter:


  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/fonts/
    - assets/svg/light/
    - assets/svg/dark/

  fonts:
    - family: fontBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: fontSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: fontMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
    - family: fontRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400


flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0F1B26"
  image: assets/png/logo.png
  image_dark: assets/png/logo.png
  android: true
  ios: true
