name: finance_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #navigation
  go_router: ^16.2.1

  #ui
  top_snackbar_flutter: ^3.3.0

  #state_managment
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  #helpers
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  mask_text_input_formatter: ^2.9.0

  #di
  injectable: ^2.5.1
  get_it: ^8.2.0

  #network
  dio: ^5.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  injectable_generator: ^2.8.1
  build_runner: ^2.7.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

